// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://jwohhjrflmxicjlgjyis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3b2hoanJmbG14aWNqbGdqeWlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxMDkxMDgsImV4cCI6MjA5MTY4NTEwOH0.i3JRlzYCrc3zDE9Ump7btuP3ePN-RBd33GLS2xhP57k";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
  },
});